// Generated by https://quicktype.io
import type { Movement } from "$lib/types/movement";


export const addMovement = async (movement: Movement) => {
    try {
        const res = await fetch('/api/movement', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(movement)
        });
        const data = await res.json();
        return data;
    } catch (error) {
        console.error('Error:', error);
        throw error;
    }
};